# CCometixLine Model Configuration
# This file defines model display names and context limits for different AI models
# File location: ~/.claude/ccline/models.toml

# Default context limit for unknown models
default_context_limit = 200000

# Model configurations
# Each [[models]] section defines a model pattern and its properties
# Order matters: first match wins, so put more specific patterns first

# Current Claude models
[[models]]
pattern = "claude-sonnet-4"
display_name = "Sonnet 4"
context_limit = 200000

[[models]]
pattern = "claude-3-5-sonnet"
display_name = "Sonnet 3.5"
context_limit = 200000

# Example: Add custom models here
# [[models]]
# pattern = "glm-4.5"
# display_name = "GLM-4.5"
# context_limit = 128000